# Generated by Django 5.2.7 on 2025-10-15 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='QuizType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=300, verbose_name='Question')),
                ('right_answer', models.CharField(blank=True, max_length=300, verbose_name='Right Answer')),
                ('wrong_answer_1', models.CharField(blank=True, max_length=300, verbose_name='Wrong Answer 1')),
                ('wrong_answer_2', models.CharField(blank=True, max_length=300, verbose_name='Wrong Answer 2')),
                ('wrong_answer_3', models.CharField(blank=True, max_length=300, verbose_name='Wrong Answer 3')),
                ('difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_types', to='quiz.quizdifficulty', verbose_name='Type')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_types', to='quiz.quiztype', verbose_name='Type')),
            ],
        ),
    ]
