# Generated by Django 5.2.7 on 2025-10-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizdifficulty_quiztype_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='corrects',
            field=models.IntegerField(default=0, verbose_name='Corrects'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wrongs',
            field=models.IntegerField(default=0, verbose_name='Wrongs'),
        ),
    ]
