# Generated by Django 5.2.7 on 2025-10-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_customuser_corrects_customuser_wrongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
    ]
