# Generated by Django 5.2.7 on 2025-10-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_customuser_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='owner',
            field=models.BooleanField(default=False, verbose_name='Owner'),
        ),
    ]
